### ISSUE TITLE
How are .cu files created?

### ISSUE THREAD

**Issue by JustFragger** [JayDDee/suprminer-jdd#1]
Hey @JayDDee,
This is not an issue, but question instead.

I would like to ask if you know how **.cu** (CUDA) files are coded, I have been studying tpruvot"s code (commits also), everything is understandable but I dont know how to code this CUDA files to work with ccminer hashing properly ...
Can you give any tips where to start?

Thanks in advance!

**Comment by JayDDee** [comment]
I can't really help you, I'm not a Cuda coder. Cuda source files contain many extensions to c/c++ to build GPU kernels.
The first thing to understand is how to distinguish host (CPU) code from device (GPU) code. I suggest digging into the
Cuda documentation.

**Comment by JustFragger** [comment]
Thanks for something at least.
I will check out CUDA documentation, when I will have free time.

Thanks, closing this issue.
