### ISSUE TITLE
Solo on windows 10

### ISSUE THREAD

**Issue by sachinverma1** [JayDDee/suprminer-jdd#2]
Hi,

I want to know weather this miner works on windows 10.. I want to solo mine litecoin (scrypt)  Algo.. On my localhost With my 4gb Nvidia GPU..
If it does work on windows then please tell me any documentation which can help me to set up.

Thank you

**Comment by JayDDee** [comment]
First I don't provide any support for Suprminer. Second it doesn't work with Windows, solo or stratum. Third you don't need it to mine scrypt. You can use tpruvot ccminer and it works on Windows 10 but I can't say about solo mining.

**Comment by sachinverma1** [comment]
Hi.. Thank you for your response... I tried tpruvot ccminer... But it
doesn't works...

Well it's ok...
